runtime: python311

handlers:
  # Serve Vite static assets (JS/CSS)
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/(.*)
    http_headers:
      Cache-Control: no-cache

  # Serve index.html for SPA routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
